# Generated by Django 5.2.4 on 2025-07-29 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haunt_ops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventvolunteers',
            options={'managed': False},
        ),
    ]
