# Generated by Django 5.2.4 on 2025-07-08 05:16

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haunt_ops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2025, 7, 7, 22, 14, 30, 169529)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(default='first', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuser',
            name='last_activity',
            field=models.CharField(default=datetime.datetime(2025, 7, 7, 22, 15, 10, 688506), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(default='last', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuser',
            name='username',
            field=models.CharField(default='n/a', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 7, 22, 16, 8, 109647)),
            preserve_default=False,
        ),
    ]
