# Generated by Django 5.2.4 on 2025-07-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haunt_ops', '0003_events_groups_alter_appuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='address',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='ice_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='ice_phone',
            field=models.CharField(default='unknown', max_length=12),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='ice_relationship',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='image_url',
            field=models.CharField(default='unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='phone1',
            field=models.CharField(default='unknown', max_length=12),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='phone2',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='tshirt_size',
            field=models.CharField(default='unknown', max_length=12),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='zipcode',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
