# Generated by Django 5.2.4 on 2025-07-10 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haunt_ops', '0005_alter_appuser_allergies_alter_appuser_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventchecklist',
            old_name='onsite',
            new_name='signed_in',
        ),
        migrations.AddField(
            model_name='appuser',
            name='point_total',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GroupVolunteers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haunt_ops.groups')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_volunteers',
            },
        ),
    ]
