# Generated by Django 5.2.4 on 2025-07-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haunt_ops', '0006_rename_onsite_eventchecklist_signed_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='haunt_experience',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
