app_name: "thia"
version: 1.0
debug_mode: true

database:
  host: "localhost"
  port: 5432
  username: "zack"
  password: "ENV"
  name: "thia"



logging:
  level: "INFO"
  file: "etl.log"

features:
  enable_feature_a: true
  enable_feature_b: false




csv_header_name_mapping:
  "Unnamed: 0": "id"
  "F.Name": "first_name"
  "L.Name" : "last_name"
  "E-Mail" : "email"
  "Phone 1" : "phone1"
  "Phone 2" : "phone2"
  "Primary Phone" : "phone1"
  "Date of Birth" : "date_of_birth"
  "E-mail Blocked" : "email_blocked"
  "E-Mail Blocked" : "email_blocked"
  "Phone Blocked" : "phone_verified"
  "Emergency Contact (First Name, Last Name)": "ice_name"
  "Emergency Contact  (First Name, Last Name)": "ice_name"
  "Emergency Contact Relation": "ice_relationship"
  "Emergency Contact Phone Number": "ice_phone"
  "Emergency Contact Phone Number ": "ice_phone"
  "Postal Code": "zipcode"
  "T-Shirt Size": "tshirt_size"
  "State/Province": "state"
  "Added": "start_date"
  "Last Activity": "last_activity"
  "Are you under 18 years of age?": "under_18"
  "Would you be able to wear a character mask" : "wear_mask"
  "How did you hear about us" : "referral_source"
  "Haunt Interests" : "haunt_experience"
  "Allergies": "allergies"
  "Notes": "notes"
  "City": "city"
  "Address": "address"
  "Country": "country"
  "Company": "company"
  "Waiver": "waiver"
  "Event(s)": "events"
  "Member of Group(s)": "groups"
  "Hours": "hours"
  "Points": "points"
  "Event": "event_name"
  "S.Time": "start_time"
  "E.Time": "end_time"
  "Task": "task"
  "Date": "date"
  "Slot Column": "slot_column"
  "Slot Row": "slot_row"
  "Signed In": "signed_in"
  "Conflict": "conflict"
  "Confirmed": "confirmed"
  "Waitlist": "waitlist"
  "Full Address": "full_address"




groups:
  "Build Team": 1
  "Build Team Members": 1
  "Bungee" : 1
  "Costumes": 1
  "Event Signup": 1
  "Floor Manager": 1
  "Floor Manager Assistant": 1
  "Front of the House/Ticket Booth": 1
  "Haunt Technician": 1
  "Key Masters" : 1
  "Line Entertainment" : 1
  "Main Greeter/ Front Gate" : 1
  "Makeup": 1
  "Makeup Lead": 1
  "Photographer" : 1
  "Room Actors": 1
  "Scare Actor": 1
  "Social Media": 1
  "Threshold Guardian" : 1
  "Ticket Booth" : 1
  "Ticket Taker/Door Control" : 1
  "Zipline" : 1







