browser_config:
   chrome_options:
    - "--disable-gpu"
    - "--enable-logging"
    - "--v=1"
    - "--headless=new"
   download_directory: "haunt_ops/downloads/"

login:
  url: "https://ivolunteer.com/administrator-login/"
  org_id: "the-haunt"
  admin_email: "tedspecht@gmail.com"
  password: 'ENV'

